GET http://localhost:5000/api/v1/persons 

###
POST http://localhost:5000/api/v1/persons
Content-Type: application/json

{ "username" : "Laboge" }

###
PUT http://localhost:5000/api/v1/persons/3
Content-Type: application/json

{ "username" : "Laboge" }
###
DELETE http://localhost:5000/api/v1/persons/3